$axure.loadCurrentPage({
  "url":"new_page_1.html",
  "generationDate":new Date(1386580811958.53),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"da91d262c0154210956f37baf73b3230",
    "type":"Axure:Page",
    "name":"New Page 1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5286b3e84e6a47a9a373e843ffd0dd20",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f23e1be57194ce79be30037213d8180",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"efad9823dabb4918809dd9a01d64145a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"35px",
            "location":{
              "x":0,
              "y":1},
            "size":{
              "width":640,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c784b1a923041cf9b47228d287b2d75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"35px",
                "location":{
                  "x":0,
                  "y":1},
                "size":{
                  "width":640,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u2.png"}},
{
          "id":"693b3dd9b41a48c9803827359d725aea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":26},
            "size":{
              "width":50,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a54572128cd4319bb562340dbea3a29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22,
                  "y":26},
                "size":{
                  "width":50,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Page 3 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"page_3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u4.png"}},
{
          "id":"cf7f40209bcf423d90857e8f98c354cc",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":50,
              "y":122},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd5be48b5ddb4f418d54c3645eb021a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":50,
                  "y":122},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open wordcross in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"wordcross.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u6.png"}},
{
          "id":"463f4541487f48108b5f481c083c2064",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":245,
              "y":122},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1770835d5ad64803975ad23ac5bcbfd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":245,
                  "y":122},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u6.png"}},
{
          "id":"094147bc896d475b87cf58520f38f919",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":440,
              "y":122},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83af89b3e0c5480cb4738c5aced9ba1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":440,
                  "y":122},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u6.png"}},
{
          "id":"0d0bef0e8f28442dacb7852017005aa6",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":50,
              "y":330},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5af5b70c389f4c4bbfd10770bedc9f9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":50,
                  "y":330},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u6.png"}},
{
          "id":"9d732ea63b6042bfb7b2abf35d1f9b73",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":245,
              "y":330},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37bf244e4d4f445c92654e4baa081faf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":245,
                  "y":330},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u6.png"}},
{
          "id":"30c8fa22db4244f2855888d8b51c24c5",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":440,
              "y":330},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9c6b457141f4d3f8b5ebcdb9eaef811",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":440,
                  "y":330},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u6.png"}},
{
          "id":"9186a247c00145f68c9f0dd75e5ff8e1",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":50,
              "y":540},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad0e024b8c8a42939083e548366b06ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":50,
                  "y":540},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u6.png"}},
{
          "id":"4cb26fef955a4fec9cd6b8e3f295c3c8",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":245,
              "y":540},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5254436fc8394732b113127985112fb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":245,
                  "y":540},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u6.png"}},
{
          "id":"810b42a59edb4c4cb08b7ebb3ea890fe",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":440,
              "y":540},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cef907a9b2254ddebe992a588a7b6c51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":440,
                  "y":540},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u6.png"}},
{
          "id":"232fd43325784b129cb6e7155ab3f3ce",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":50,
              "y":747},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e95b17c69a8c4f32860c1d4e58a0075e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":50,
                  "y":747},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u6.png"}},
{
          "id":"9197b9bfb1284a47bee7d2581b6dec85",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":245,
              "y":747},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1219c43503104bfb95b8892ef0ed92db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":245,
                  "y":747},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u6.png"}},
{
          "id":"868ed307ef9941d097db01023f4a19ec",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":440,
              "y":747},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5927547741d24c8e98b46c452991d3b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":440,
                  "y":747},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u6.png"}},
{
          "id":"0611c6a170214d338a9fd69f81a131df",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":50,
              "y":959.999938964844},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ffccbefbe374443bdd4dee0b90f52de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":50,
                  "y":959.999938964844},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u6.png"}},
{
          "id":"b9207286dc3c478fb415a39e5f803c70",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":245,
              "y":959.999938964844},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"842c20038fa44742a1c3ac2b460d63b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":245,
                  "y":959.999938964844},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u6.png"}},
{
          "id":"a15fd5e8546642f0b4432ff6d109a1f8",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":440,
              "y":959.999938964844},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aded86030d99406d8abf9ed39c158d2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":440,
                  "y":959.999938964844},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u6.png"}},
{
          "id":"a2bb677e47fe42f8baab2486d3af0b14",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":148,
              "y":233},
            "size":{
              "width":35,
              "height":35},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a0d8b2d3d444e65a68a9dfdf219ed55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":148,
                  "y":233},
                "size":{
                  "width":35,
                  "height":35},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/new_page_1/u36.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "5286b3e84e6a47a9a373e843ffd0dd20":{
      "scriptId":"u0"},
    "5f23e1be57194ce79be30037213d8180":{
      "scriptId":"u1"},
    "efad9823dabb4918809dd9a01d64145a":{
      "scriptId":"u2"},
    "5c784b1a923041cf9b47228d287b2d75":{
      "scriptId":"u3"},
    "693b3dd9b41a48c9803827359d725aea":{
      "scriptId":"u4"},
    "2a54572128cd4319bb562340dbea3a29":{
      "scriptId":"u5"},
    "cf7f40209bcf423d90857e8f98c354cc":{
      "scriptId":"u6"},
    "fd5be48b5ddb4f418d54c3645eb021a2":{
      "scriptId":"u7"},
    "463f4541487f48108b5f481c083c2064":{
      "scriptId":"u8"},
    "1770835d5ad64803975ad23ac5bcbfd4":{
      "scriptId":"u9"},
    "094147bc896d475b87cf58520f38f919":{
      "scriptId":"u10"},
    "83af89b3e0c5480cb4738c5aced9ba1f":{
      "scriptId":"u11"},
    "0d0bef0e8f28442dacb7852017005aa6":{
      "scriptId":"u12"},
    "5af5b70c389f4c4bbfd10770bedc9f9a":{
      "scriptId":"u13"},
    "9d732ea63b6042bfb7b2abf35d1f9b73":{
      "scriptId":"u14"},
    "37bf244e4d4f445c92654e4baa081faf":{
      "scriptId":"u15"},
    "30c8fa22db4244f2855888d8b51c24c5":{
      "scriptId":"u16"},
    "b9c6b457141f4d3f8b5ebcdb9eaef811":{
      "scriptId":"u17"},
    "9186a247c00145f68c9f0dd75e5ff8e1":{
      "scriptId":"u18"},
    "ad0e024b8c8a42939083e548366b06ae":{
      "scriptId":"u19"},
    "4cb26fef955a4fec9cd6b8e3f295c3c8":{
      "scriptId":"u20"},
    "5254436fc8394732b113127985112fb8":{
      "scriptId":"u21"},
    "810b42a59edb4c4cb08b7ebb3ea890fe":{
      "scriptId":"u22"},
    "cef907a9b2254ddebe992a588a7b6c51":{
      "scriptId":"u23"},
    "232fd43325784b129cb6e7155ab3f3ce":{
      "scriptId":"u24"},
    "e95b17c69a8c4f32860c1d4e58a0075e":{
      "scriptId":"u25"},
    "9197b9bfb1284a47bee7d2581b6dec85":{
      "scriptId":"u26"},
    "1219c43503104bfb95b8892ef0ed92db":{
      "scriptId":"u27"},
    "868ed307ef9941d097db01023f4a19ec":{
      "scriptId":"u28"},
    "5927547741d24c8e98b46c452991d3b6":{
      "scriptId":"u29"},
    "0611c6a170214d338a9fd69f81a131df":{
      "scriptId":"u30"},
    "4ffccbefbe374443bdd4dee0b90f52de":{
      "scriptId":"u31"},
    "b9207286dc3c478fb415a39e5f803c70":{
      "scriptId":"u32"},
    "842c20038fa44742a1c3ac2b460d63b9":{
      "scriptId":"u33"},
    "a15fd5e8546642f0b4432ff6d109a1f8":{
      "scriptId":"u34"},
    "aded86030d99406d8abf9ed39c158d2c":{
      "scriptId":"u35"},
    "a2bb677e47fe42f8baab2486d3af0b14":{
      "scriptId":"u36"},
    "5a0d8b2d3d444e65a68a9dfdf219ed55":{
      "scriptId":"u37"}}});