$axure.loadCurrentPage({
  "url":"page_2.html",
  "generationDate":new Date(1386580811751.52),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8e7914c32440415c8a942c70abc935b2",
    "type":"Axure:Page",
    "name":"Page 2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c61de68c64f94715b832cfaf4ab9a822",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86de4511214c45c6a311a09629f94eb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"f88dad94437c4d988e8abb3fec170147",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"35px",
            "location":{
              "x":0,
              "y":1},
            "size":{
              "width":640,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6296300d1bb400389d8d8c368b04203",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"35px",
                "location":{
                  "x":0,
                  "y":1},
                "size":{
                  "width":640,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u2.png"}},
{
          "id":"3aa701814e5c43eeb9367be785250ec3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":26},
            "size":{
              "width":50,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a2857297a434116b1c93c3c3d130263",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22,
                  "y":26},
                "size":{
                  "width":50,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u4.png"}},
{
          "id":"234f6aa007f943d3900c7314593b3aab",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"35px",
            "location":{
              "x":220,
              "y":260},
            "size":{
              "width":200,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"870fca75c8244c5599f70000633fd9ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"35px",
                "location":{
                  "x":220,
                  "y":260},
                "size":{
                  "width":200,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_2/u6.png"}},
{
          "id":"ca93ddc32eab4691b3818138339766d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"30px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":108,
              "y":120},
            "size":{
              "width":425,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3b06d18d478434682a320ab7219ccaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"30px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":120},
                "size":{
                  "width":425,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba1225ff904741bebf402b07457643a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "location":{
              "x":102,
              "y":546},
            "size":{
              "width":61,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"deba0b5bd25c4fbca7b9aa40a22a1af8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "location":{
                  "x":102,
                  "y":546},
                "size":{
                  "width":61,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"305a9dc56cc147ebaca58cb334c2dd77",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "location":{
              "x":102,
              "y":634},
            "size":{
              "width":61,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4117f0a987ab45b4a28b69876dfc0543",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "location":{
                  "x":102,
                  "y":634},
                "size":{
                  "width":61,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3204e02566d34ec3945b76d7817aaf0b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":538},
            "size":{
              "width":350,
              "height":60}},
          "adaptiveStyles":{
}},
{
          "id":"d78f300ce3b948869c6224e8a151c533",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":630},
            "size":{
              "width":350,
              "height":60}},
          "adaptiveStyles":{
}},
{
          "id":"ed4a8be3603d4ebab76e2da8b308ccb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "location":{
              "x":438,
              "y":730},
            "size":{
              "width":100,
              "height":60},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30a44034d7884d3b8572671e4e61dc54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "location":{
                  "x":438,
                  "y":730},
                "size":{
                  "width":100,
                  "height":60},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open wordcross in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"wordcross.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_2/u16.png"}},
{
          "id":"6b561c679b9c4ea99e090102d21b640f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "location":{
              "x":530,
              "y":11},
            "size":{
              "width":100,
              "height":60},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"003ae855e518482484e9deec7e72ff49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "location":{
                  "x":530,
                  "y":11},
                "size":{
                  "width":100,
                  "height":60},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 注册 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"注册.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_2/u18.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c61de68c64f94715b832cfaf4ab9a822":{
      "scriptId":"u0"},
    "86de4511214c45c6a311a09629f94eb7":{
      "scriptId":"u1"},
    "f88dad94437c4d988e8abb3fec170147":{
      "scriptId":"u2"},
    "b6296300d1bb400389d8d8c368b04203":{
      "scriptId":"u3"},
    "3aa701814e5c43eeb9367be785250ec3":{
      "scriptId":"u4"},
    "9a2857297a434116b1c93c3c3d130263":{
      "scriptId":"u5"},
    "234f6aa007f943d3900c7314593b3aab":{
      "scriptId":"u6"},
    "870fca75c8244c5599f70000633fd9ef":{
      "scriptId":"u7"},
    "ca93ddc32eab4691b3818138339766d6":{
      "scriptId":"u8"},
    "b3b06d18d478434682a320ab7219ccaf":{
      "scriptId":"u9"},
    "ba1225ff904741bebf402b07457643a5":{
      "scriptId":"u10"},
    "deba0b5bd25c4fbca7b9aa40a22a1af8":{
      "scriptId":"u11"},
    "305a9dc56cc147ebaca58cb334c2dd77":{
      "scriptId":"u12"},
    "4117f0a987ab45b4a28b69876dfc0543":{
      "scriptId":"u13"},
    "3204e02566d34ec3945b76d7817aaf0b":{
      "scriptId":"u14"},
    "d78f300ce3b948869c6224e8a151c533":{
      "scriptId":"u15"},
    "ed4a8be3603d4ebab76e2da8b308ccb7":{
      "scriptId":"u16"},
    "30a44034d7884d3b8572671e4e61dc54":{
      "scriptId":"u17"},
    "6b561c679b9c4ea99e090102d21b640f":{
      "scriptId":"u18"},
    "003ae855e518482484e9deec7e72ff49":{
      "scriptId":"u19"}}});