$axure.loadCurrentPage({
  "url":"注册.html",
  "generationDate":new Date(1386580812341.55),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"94ceee459067418d90bfc5d366320fe8",
    "type":"Axure:Page",
    "name":"注册",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e7c061605f8b4313ad4573fad6f847e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73dcf7e12abc4dca8f9e7a0f465a4ee7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"8a0fa846161b4465b94bcc478466c20f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"35px",
            "location":{
              "x":0,
              "y":1},
            "size":{
              "width":640,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf0443a98d134779ba9e0f35608de8f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"35px",
                "location":{
                  "x":0,
                  "y":1},
                "size":{
                  "width":640,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u2.png"}},
{
          "id":"21c47ca899684eb9847f4409bd41592a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":26},
            "size":{
              "width":50,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a81bb3d13474b27990a3b9f46486135",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22,
                  "y":26},
                "size":{
                  "width":50,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u4.png"}},
{
          "id":"c465ddd95056440ab15ae21ecae34c3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "horizontalAlignment":"left",
            "location":{
              "x":20,
              "y":150},
            "size":{
              "width":600,
              "height":70},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7dbef183a75247d78eebb1803c75f38c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "horizontalAlignment":"left",
                "location":{
                  "x":20,
                  "y":150},
                "size":{
                  "width":600,
                  "height":70},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u6.png"}},
{
          "id":"784e185cd3a64b7ebb9760cd49f4c29d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "horizontalAlignment":"left",
            "location":{
              "x":20,
              "y":240},
            "size":{
              "width":600,
              "height":70},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11afe312609c44aca4742490eb489d54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "horizontalAlignment":"left",
                "location":{
                  "x":20,
                  "y":240},
                "size":{
                  "width":600,
                  "height":70},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u6.png"}},
{
          "id":"9f366cea9fdf4445bacc1d91e227c443",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "horizontalAlignment":"left",
            "location":{
              "x":20,
              "y":330},
            "size":{
              "width":600,
              "height":70},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06f8480ddb094808a05ff3432680aeae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "horizontalAlignment":"left",
                "location":{
                  "x":20,
                  "y":330},
                "size":{
                  "width":600,
                  "height":70},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u6.png"}},
{
          "id":"b8befbf389594ef8ab31815bbeab7128",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "fill":{
              "fillType":"solid",
              "color":0xFF6CBF40},
            "location":{
              "x":20,
              "y":421},
            "size":{
              "width":600,
              "height":70},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2fc1c6eb3224ea887e9ddb216d575e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6CBF40},
                "location":{
                  "x":20,
                  "y":421},
                "size":{
                  "width":600,
                  "height":70},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u12.png"}},
{
          "id":"40513c564bc340d1a759a9849050af6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"30px",
            "fontWeight":"400",
            "location":{
              "x":214.5,
              "y":530},
            "size":{
              "width":211,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bead0c5348c5409c9e65110d30c23a6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"30px",
                "fontWeight":"400",
                "location":{
                  "x":214.5,
                  "y":530},
                "size":{
                  "width":211,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e7c061605f8b4313ad4573fad6f847e5":{
      "scriptId":"u0"},
    "73dcf7e12abc4dca8f9e7a0f465a4ee7":{
      "scriptId":"u1"},
    "8a0fa846161b4465b94bcc478466c20f":{
      "scriptId":"u2"},
    "bf0443a98d134779ba9e0f35608de8f7":{
      "scriptId":"u3"},
    "21c47ca899684eb9847f4409bd41592a":{
      "scriptId":"u4"},
    "6a81bb3d13474b27990a3b9f46486135":{
      "scriptId":"u5"},
    "c465ddd95056440ab15ae21ecae34c3e":{
      "scriptId":"u6"},
    "7dbef183a75247d78eebb1803c75f38c":{
      "scriptId":"u7"},
    "784e185cd3a64b7ebb9760cd49f4c29d":{
      "scriptId":"u8"},
    "11afe312609c44aca4742490eb489d54":{
      "scriptId":"u9"},
    "9f366cea9fdf4445bacc1d91e227c443":{
      "scriptId":"u10"},
    "06f8480ddb094808a05ff3432680aeae":{
      "scriptId":"u11"},
    "b8befbf389594ef8ab31815bbeab7128":{
      "scriptId":"u12"},
    "a2fc1c6eb3224ea887e9ddb216d575e0":{
      "scriptId":"u13"},
    "40513c564bc340d1a759a9849050af6e":{
      "scriptId":"u14"},
    "bead0c5348c5409c9e65110d30c23a6b":{
      "scriptId":"u15"}}});