$axure.loadCurrentPage({
  "url":"个人中心.html",
  "generationDate":new Date(1386580812177.54),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"54f389ff7c714a6b97a29dae7a472d99",
    "type":"Axure:Page",
    "name":"个人中心",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"456e81acdd2f4eae855e8cb24ddbefb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc0ccdc4e2b24d33bedc09ad1d825af2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"b208cb0e2b7f4295a8f9cba3a2e41f79",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"35px",
            "location":{
              "x":0,
              "y":1},
            "size":{
              "width":640,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0663acb265f049cfb1512459c74d3854",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"35px",
                "location":{
                  "x":0,
                  "y":1},
                "size":{
                  "width":640,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u2.png"}},
{
          "id":"6cf94a5bd0c7414380f386fdfe3faa74",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":26},
            "size":{
              "width":50,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2101d7b4f5ab40b3b24bfac7858dc263",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22,
                  "y":26},
                "size":{
                  "width":50,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u4.png"}},
{
          "id":"8a60f945d4d941638ba2166962bd60e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF3F3F3},
            "location":{
              "x":0,
              "y":82},
            "size":{
              "width":640,
              "height":254},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"389868a8a1ca4792b4057ad03b81f127",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF3F3F3},
                "location":{
                  "x":0,
                  "y":82},
                "size":{
                  "width":640,
                  "height":254},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心/u6.png"}},
{
          "id":"e24efe50c8794b85b6f1039ba4887ea4",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":144},
            "size":{
              "width":130,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0cefa78a8e9489392306e5f9c026593",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":144},
                "size":{
                  "width":130,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心/u8.png"}},
{
          "id":"614b03b77eed435cbacefe45fa38e950",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"35px",
            "location":{
              "x":212,
              "y":171.5},
            "size":{
              "width":94,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05a9cd05974b45bf8aab411afeae71e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"35px",
                "location":{
                  "x":212,
                  "y":171.5},
                "size":{
                  "width":94,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b948c9ba7ecb4715a99e8c77736616da",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":560,
              "y":100},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c10956b044314d85a95cb3b121e06279",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":560,
                  "y":100},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 设置 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/个人中心/u12.png"}},
{
          "id":"3f1f99dcd8584c5893d76bc354b3b75a",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":0,
              "y":336},
            "size":{
              "width":640,
              "height":80},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b84fda61cc224764a6e5cad846e82263",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":0,
                  "y":336},
                "size":{
                  "width":640,
                  "height":80},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心/u14.png"}},
{
          "id":"da64923bfe51466d9bd6d80837b319ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "location":{
              "x":212,
              "y":217.5},
            "size":{
              "width":168,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d31df0da00b84b2088fe69850d094ecd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "location":{
                  "x":212,
                  "y":217.5},
                "size":{
                  "width":168,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ede5acf73884d0f9181fda83d138d25",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":450},
            "size":{
              "width":560,
              "height":630},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"812f0f6458c34d0ba752f7ff33ddbdf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":450},
                "size":{
                  "width":560,
                  "height":630},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心/u18.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "456e81acdd2f4eae855e8cb24ddbefb1":{
      "scriptId":"u0"},
    "dc0ccdc4e2b24d33bedc09ad1d825af2":{
      "scriptId":"u1"},
    "b208cb0e2b7f4295a8f9cba3a2e41f79":{
      "scriptId":"u2"},
    "0663acb265f049cfb1512459c74d3854":{
      "scriptId":"u3"},
    "6cf94a5bd0c7414380f386fdfe3faa74":{
      "scriptId":"u4"},
    "2101d7b4f5ab40b3b24bfac7858dc263":{
      "scriptId":"u5"},
    "8a60f945d4d941638ba2166962bd60e4":{
      "scriptId":"u6"},
    "389868a8a1ca4792b4057ad03b81f127":{
      "scriptId":"u7"},
    "e24efe50c8794b85b6f1039ba4887ea4":{
      "scriptId":"u8"},
    "d0cefa78a8e9489392306e5f9c026593":{
      "scriptId":"u9"},
    "614b03b77eed435cbacefe45fa38e950":{
      "scriptId":"u10"},
    "05a9cd05974b45bf8aab411afeae71e7":{
      "scriptId":"u11"},
    "b948c9ba7ecb4715a99e8c77736616da":{
      "scriptId":"u12"},
    "c10956b044314d85a95cb3b121e06279":{
      "scriptId":"u13"},
    "3f1f99dcd8584c5893d76bc354b3b75a":{
      "scriptId":"u14"},
    "b84fda61cc224764a6e5cad846e82263":{
      "scriptId":"u15"},
    "da64923bfe51466d9bd6d80837b319ee":{
      "scriptId":"u16"},
    "d31df0da00b84b2088fe69850d094ecd":{
      "scriptId":"u17"},
    "7ede5acf73884d0f9181fda83d138d25":{
      "scriptId":"u18"},
    "812f0f6458c34d0ba752f7ff33ddbdf9":{
      "scriptId":"u19"}}});