$axure.loadCurrentPage({
  "url":"wordcross.html",
  "generationDate":new Date(1386580811680.52),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0e2afc8c8df941faad0c7b906b513ab5",
    "type":"Axure:Page",
    "name":"wordcross",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"83ff89aedbd64ef5af49bf4632f4bb1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3143eb6bf4434b969270e99ba47724b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"0c78c2ccdece4b6f930c3931b1b65413",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"35px",
            "size":{
              "width":640,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"167e11a4bd4b40b480afc44f35bed9cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"35px",
                "size":{
                  "width":640,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u2.png"}},
{
          "id":"1a23114989c14db785dd5ae434de7ad8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":26},
            "size":{
              "width":50,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcfa3785bbcf4f3ebff797c59ca77b40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22,
                  "y":26},
                "size":{
                  "width":50,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Page 1 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"page_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u4.png"}},
{
          "id":"3aee3e285b0d414d9ad69c6e9d9565ae",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFEEEEEE},
            "location":{
              "x":0,
              "y":79},
            "size":{
              "width":640,
              "height":150},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67604e7cc49c47d59f7a5a094fecf487",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEEEEEE},
                "location":{
                  "x":0,
                  "y":79},
                "size":{
                  "width":640,
                  "height":150},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u6.png"}},
{
          "id":"31f43bc1953a482d9f0ff9bbe66a87f4",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":0,
              "y":229},
            "size":{
              "width":640,
              "height":671}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fa0a08d59d04ae1a540fbe7bd8d2619",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":0,
                  "y":229},
                "size":{
                  "width":640,
                  "height":671}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u8.png"}},
{
          "id":"b80bd7920f014e049c813fc6e3f0294d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":2,
              "y":907},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01e8dbdfd32e4daa8aa40d974dcb3515",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2,
                  "y":907},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"10185be1fbb04ab5ac5270f52418d1b9",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":907},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eef106b942d34403be951aa576988dc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":66,
                  "y":907},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"78e99095f86148179ea29dfca6f75bdb",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":907},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40dfb7310a1c4841a54650db54cc967c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":907},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"22a81312e6e54731853cdfaa9a719e3d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":194,
              "y":907},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"476a2794c4224b7b9c15d383fae56e79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":194,
                  "y":907},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"e670ab47b8fd4205b2ba292bdc70aec5",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":258,
              "y":907},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"718c546ed433407aa512fefa5cd75f72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":258,
                  "y":907},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"ef0fc0e640324361a3e3461ce9aabc43",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":322,
              "y":907},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b3ce9b422064facb7e4af45898816dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":322,
                  "y":907},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"a8c003dbc9d44301b780ecf7b4ad0262",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":386,
              "y":907},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8dc63e24d5344ebb8eb3cb3e06dc85c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":386,
                  "y":907},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"f36033eb34a940c0a81586763b2c4a03",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":907},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f8f95715ad74bebbdf33b8a67519b1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":907},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"092c6055fee3495b83f169d5a85c7860",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":512,
              "y":907},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed8bbfdaaabf47a39bb9fedcaf45c405",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":512,
                  "y":907},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"b1ac069eed0d4cab805438ee6454d252",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":576,
              "y":907},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9634fb0d18eb45689344007e57a7d67b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":576,
                  "y":907},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"01d7f606a1e24f87b1da2d7281a5dec1",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":982},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30df813be78046f39d179aef3160b6fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":982},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"8cbcf5baefa440f38cd7b0672e5f649f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":98,
              "y":982},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbdafb0c4be540d18958eb244c2f70f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":98,
                  "y":982},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"c79f44fecfcd4b7ba9c10ccf981930f5",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":162,
              "y":982},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae335d5da283498ab9032ab00180602d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":162,
                  "y":982},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"b170a015e81f46499f69eee0f1f265bb",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":226,
              "y":982},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab8ef150f9e64f9b92a5258b35d9ee62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":226,
                  "y":982},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"96e5466ff6534e938881c058834fee69",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":982},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"124b27d598d14682851a632e95781df3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":982},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"dcb1de0a4cdf488ab58aebccd1b0b0ca",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":982},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff0d42110b794419aba82b027994c636",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":354,
                  "y":982},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"63937bc66ddb448d91d974a7326274b1",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":418,
              "y":982},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c303a6f3de334a4c80f582c198ee83a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":418,
                  "y":982},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"dcc3af03ed4245f4a5e25e82c55bdb7f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":982},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b75917110d54a649bcd960de86b2b8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":982},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"1dda68f259154b44ae13691086072d76",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":544,
              "y":982},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a47300135fc54c8da1813a0f428e34e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":544,
                  "y":982},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"d677803c50a8485ba23cdd400cd1b439",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":98,
              "y":1055},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a48dda2898334452ab57310cad336fc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":98,
                  "y":1055},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"d3bed224b8cb4827a42ee54b4d06a13c",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":162,
              "y":1055},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09a0f9cd20ab433bb8d8c772b7d19556",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":162,
                  "y":1055},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"cb6c38e6c5a5420191000c99a9b9e483",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":226,
              "y":1055},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24db76d43b544ede8ad1b4ff3769c40c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":226,
                  "y":1055},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"37c2fcf330954f77b17c940d95ddf597",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":1055},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7db90f8f7cb4325ae9bc69b58cd3202",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":1055},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"ecbd59689bea402a974bb877254085ed",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":1055},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5abbe3279d3d42c3ac6a776d9d649c98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":354,
                  "y":1055},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"a9b2ab55d1374c70a9a0ebd874b9bfd2",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":418,
              "y":1055},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70e31698e1f14388981ef6ce0c0bafa3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":418,
                  "y":1055},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"6ebbf7fd00664d458e406cffc6c92034",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":1055},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"574a9efd95ad409f90bfd02ad1f4bb4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":1055},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u10.png"}},
{
          "id":"1ac789ace67c4dccb8cb0df98f81691f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"35px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":546,
              "y":1055},
            "size":{
              "width":63,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef14f161e06a44bca7ae83fbbb885074",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"35px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":546,
                  "y":1055},
                "size":{
                  "width":63,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u62.png"}},
{
          "id":"15f1e0d9c6284099ae7da6f0807b8696",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":556,
              "y":1074},
            "size":{
              "width":42,
              "height":32},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dbf1cca996743e8b6b4f5cd1cf8aa70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":556,
                  "y":1074},
                "size":{
                  "width":42,
                  "height":32},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wordcross/u64.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "83ff89aedbd64ef5af49bf4632f4bb1d":{
      "scriptId":"u0"},
    "3143eb6bf4434b969270e99ba47724b9":{
      "scriptId":"u1"},
    "0c78c2ccdece4b6f930c3931b1b65413":{
      "scriptId":"u2"},
    "167e11a4bd4b40b480afc44f35bed9cd":{
      "scriptId":"u3"},
    "1a23114989c14db785dd5ae434de7ad8":{
      "scriptId":"u4"},
    "fcfa3785bbcf4f3ebff797c59ca77b40":{
      "scriptId":"u5"},
    "3aee3e285b0d414d9ad69c6e9d9565ae":{
      "scriptId":"u6"},
    "67604e7cc49c47d59f7a5a094fecf487":{
      "scriptId":"u7"},
    "31f43bc1953a482d9f0ff9bbe66a87f4":{
      "scriptId":"u8"},
    "9fa0a08d59d04ae1a540fbe7bd8d2619":{
      "scriptId":"u9"},
    "b80bd7920f014e049c813fc6e3f0294d":{
      "scriptId":"u10"},
    "01e8dbdfd32e4daa8aa40d974dcb3515":{
      "scriptId":"u11"},
    "10185be1fbb04ab5ac5270f52418d1b9":{
      "scriptId":"u12"},
    "eef106b942d34403be951aa576988dc5":{
      "scriptId":"u13"},
    "78e99095f86148179ea29dfca6f75bdb":{
      "scriptId":"u14"},
    "40dfb7310a1c4841a54650db54cc967c":{
      "scriptId":"u15"},
    "22a81312e6e54731853cdfaa9a719e3d":{
      "scriptId":"u16"},
    "476a2794c4224b7b9c15d383fae56e79":{
      "scriptId":"u17"},
    "e670ab47b8fd4205b2ba292bdc70aec5":{
      "scriptId":"u18"},
    "718c546ed433407aa512fefa5cd75f72":{
      "scriptId":"u19"},
    "ef0fc0e640324361a3e3461ce9aabc43":{
      "scriptId":"u20"},
    "1b3ce9b422064facb7e4af45898816dd":{
      "scriptId":"u21"},
    "a8c003dbc9d44301b780ecf7b4ad0262":{
      "scriptId":"u22"},
    "b8dc63e24d5344ebb8eb3cb3e06dc85c":{
      "scriptId":"u23"},
    "f36033eb34a940c0a81586763b2c4a03":{
      "scriptId":"u24"},
    "0f8f95715ad74bebbdf33b8a67519b1e":{
      "scriptId":"u25"},
    "092c6055fee3495b83f169d5a85c7860":{
      "scriptId":"u26"},
    "ed8bbfdaaabf47a39bb9fedcaf45c405":{
      "scriptId":"u27"},
    "b1ac069eed0d4cab805438ee6454d252":{
      "scriptId":"u28"},
    "9634fb0d18eb45689344007e57a7d67b":{
      "scriptId":"u29"},
    "01d7f606a1e24f87b1da2d7281a5dec1":{
      "scriptId":"u30"},
    "30df813be78046f39d179aef3160b6fb":{
      "scriptId":"u31"},
    "8cbcf5baefa440f38cd7b0672e5f649f":{
      "scriptId":"u32"},
    "fbdafb0c4be540d18958eb244c2f70f1":{
      "scriptId":"u33"},
    "c79f44fecfcd4b7ba9c10ccf981930f5":{
      "scriptId":"u34"},
    "ae335d5da283498ab9032ab00180602d":{
      "scriptId":"u35"},
    "b170a015e81f46499f69eee0f1f265bb":{
      "scriptId":"u36"},
    "ab8ef150f9e64f9b92a5258b35d9ee62":{
      "scriptId":"u37"},
    "96e5466ff6534e938881c058834fee69":{
      "scriptId":"u38"},
    "124b27d598d14682851a632e95781df3":{
      "scriptId":"u39"},
    "dcb1de0a4cdf488ab58aebccd1b0b0ca":{
      "scriptId":"u40"},
    "ff0d42110b794419aba82b027994c636":{
      "scriptId":"u41"},
    "63937bc66ddb448d91d974a7326274b1":{
      "scriptId":"u42"},
    "c303a6f3de334a4c80f582c198ee83a4":{
      "scriptId":"u43"},
    "dcc3af03ed4245f4a5e25e82c55bdb7f":{
      "scriptId":"u44"},
    "2b75917110d54a649bcd960de86b2b8d":{
      "scriptId":"u45"},
    "1dda68f259154b44ae13691086072d76":{
      "scriptId":"u46"},
    "a47300135fc54c8da1813a0f428e34e1":{
      "scriptId":"u47"},
    "d677803c50a8485ba23cdd400cd1b439":{
      "scriptId":"u48"},
    "a48dda2898334452ab57310cad336fc0":{
      "scriptId":"u49"},
    "d3bed224b8cb4827a42ee54b4d06a13c":{
      "scriptId":"u50"},
    "09a0f9cd20ab433bb8d8c772b7d19556":{
      "scriptId":"u51"},
    "cb6c38e6c5a5420191000c99a9b9e483":{
      "scriptId":"u52"},
    "24db76d43b544ede8ad1b4ff3769c40c":{
      "scriptId":"u53"},
    "37c2fcf330954f77b17c940d95ddf597":{
      "scriptId":"u54"},
    "e7db90f8f7cb4325ae9bc69b58cd3202":{
      "scriptId":"u55"},
    "ecbd59689bea402a974bb877254085ed":{
      "scriptId":"u56"},
    "5abbe3279d3d42c3ac6a776d9d649c98":{
      "scriptId":"u57"},
    "a9b2ab55d1374c70a9a0ebd874b9bfd2":{
      "scriptId":"u58"},
    "70e31698e1f14388981ef6ce0c0bafa3":{
      "scriptId":"u59"},
    "6ebbf7fd00664d458e406cffc6c92034":{
      "scriptId":"u60"},
    "574a9efd95ad409f90bfd02ad1f4bb4b":{
      "scriptId":"u61"},
    "1ac789ace67c4dccb8cb0df98f81691f":{
      "scriptId":"u62"},
    "ef14f161e06a44bca7ae83fbbb885074":{
      "scriptId":"u63"},
    "15f1e0d9c6284099ae7da6f0807b8696":{
      "scriptId":"u64"},
    "8dbf1cca996743e8b6b4f5cd1cf8aa70":{
      "scriptId":"u65"}}});