$axure.loadCurrentPage({
  "url":"page_1.html",
  "generationDate":new Date(1386580811515.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b9ee2f7a6ef84adfa3200faed43d2e03",
    "type":"Axure:Page",
    "name":"Page 1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"aef0336e60f9476ea07dbe5a7cac93d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34be48d7915c487484037d05c2c6e9b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"b047772a2efe43339c9890dcbfc2c6ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"35px",
            "location":{
              "x":0,
              "y":1},
            "size":{
              "width":640,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7d3b3fd0ede4684b628c9836608e6a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"35px",
                "location":{
                  "x":0,
                  "y":1},
                "size":{
                  "width":640,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u2.png"}},
{
          "id":"24659d42b3734cfd90bb0f054f02eb17",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":26},
            "size":{
              "width":50,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a802fcb325b41e283e79dd42eb78fb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22,
                  "y":26},
                "size":{
                  "width":50,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u4.png"}},
{
          "id":"ab813d6f996c4482b08d6aa0e001e016",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":122},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfcf9573fe044221aed70c5d3a2df349",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":122},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open wordcross in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"wordcross.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u6.png"}},
{
          "id":"aa208fb8851f4615a3a68e364d25fbc3",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":122},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18da56e962aa4c0ab51a577a7e45a5f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":245,
                  "y":122},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u6.png"}},
{
          "id":"a0ec344c6abf4fa89dbe8d37574a7e22",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":122},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3de48dcb85c84f35b173ef07e3787a0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":122},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u6.png"}},
{
          "id":"51c37d64b88a4a31a5650023cfbac193",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":310},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81d49714c4a645dbaa891dd1ae00d91a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":310},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u6.png"}},
{
          "id":"b6947cc1e07d4c679afe7f28de3d2fb7",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":310},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"040e9555ae264551ba26c1442a8b5962",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":245,
                  "y":310},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u6.png"}},
{
          "id":"2d7e991124ea453e80536276dace1a39",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":310},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e20c323155694736b95ee8048e88d7e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":310},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u6.png"}},
{
          "id":"8d9b9e9cb9d944eab4a2b6364687da5f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":493.000030517578},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5375c91520f4380a8701a2e244ff939",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":493.000030517578},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u6.png"}},
{
          "id":"14c94c2ed5554baabaf8cc2dab27b665",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":245,
              "y":493},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08ba6be5d13b46d0aae85a9550e77b4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":245,
                  "y":493},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u20.png"}},
{
          "id":"ca3f0c4f29044288b4e4108e96070afa",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":440,
              "y":493},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94a479fc51c34087bb18950f01038105",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":440,
                  "y":493},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u20.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "aef0336e60f9476ea07dbe5a7cac93d6":{
      "scriptId":"u0"},
    "34be48d7915c487484037d05c2c6e9b6":{
      "scriptId":"u1"},
    "b047772a2efe43339c9890dcbfc2c6ff":{
      "scriptId":"u2"},
    "d7d3b3fd0ede4684b628c9836608e6a9":{
      "scriptId":"u3"},
    "24659d42b3734cfd90bb0f054f02eb17":{
      "scriptId":"u4"},
    "3a802fcb325b41e283e79dd42eb78fb8":{
      "scriptId":"u5"},
    "ab813d6f996c4482b08d6aa0e001e016":{
      "scriptId":"u6"},
    "dfcf9573fe044221aed70c5d3a2df349":{
      "scriptId":"u7"},
    "aa208fb8851f4615a3a68e364d25fbc3":{
      "scriptId":"u8"},
    "18da56e962aa4c0ab51a577a7e45a5f4":{
      "scriptId":"u9"},
    "a0ec344c6abf4fa89dbe8d37574a7e22":{
      "scriptId":"u10"},
    "3de48dcb85c84f35b173ef07e3787a0d":{
      "scriptId":"u11"},
    "51c37d64b88a4a31a5650023cfbac193":{
      "scriptId":"u12"},
    "81d49714c4a645dbaa891dd1ae00d91a":{
      "scriptId":"u13"},
    "b6947cc1e07d4c679afe7f28de3d2fb7":{
      "scriptId":"u14"},
    "040e9555ae264551ba26c1442a8b5962":{
      "scriptId":"u15"},
    "2d7e991124ea453e80536276dace1a39":{
      "scriptId":"u16"},
    "e20c323155694736b95ee8048e88d7e4":{
      "scriptId":"u17"},
    "8d9b9e9cb9d944eab4a2b6364687da5f":{
      "scriptId":"u18"},
    "e5375c91520f4380a8701a2e244ff939":{
      "scriptId":"u19"},
    "14c94c2ed5554baabaf8cc2dab27b665":{
      "scriptId":"u20"},
    "08ba6be5d13b46d0aae85a9550e77b4d":{
      "scriptId":"u21"},
    "ca3f0c4f29044288b4e4108e96070afa":{
      "scriptId":"u22"},
    "94a479fc51c34087bb18950f01038105":{
      "scriptId":"u23"}}});