$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1386580811395.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d0c8ad78dc8c4e08b45c526217cb0886",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fb7413fdc1924269815cac7df782d215",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d17f744c2b6a4d9c8ace3dc1752aac24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"9301769a44f44ab2a0d5c61bbc4ed7e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"35px",
            "location":{
              "x":95,
              "y":441},
            "size":{
              "width":450,
              "height":80},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"531568fbfc4a4affa2289d624a38fda4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"35px",
                "location":{
                  "x":95,
                  "y":441},
                "size":{
                  "width":450,
                  "height":80},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Page 1 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"page_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"3b1f9de2e2db4f8e9b4447c8bc5d0002",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"35px",
            "location":{
              "x":95,
              "y":571},
            "size":{
              "width":450,
              "height":80},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e4205be0f4f4b6fa2d6b3ba9fd3c06f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"35px",
                "location":{
                  "x":95,
                  "y":571},
                "size":{
                  "width":450,
                  "height":80},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Page 2 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"page_2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"5cf7f7b8016845b0878ed6cb199d0c4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"35px",
            "location":{
              "x":95,
              "y":701},
            "size":{
              "width":450,
              "height":80},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5c4ee5157ea4f77aac8f219126c7b93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"35px",
                "location":{
                  "x":95,
                  "y":701},
                "size":{
                  "width":450,
                  "height":80},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Page 3 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"page_3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"72a2d3179bb74b23ab35e43d8fd659ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"40px",
            "location":{
              "x":465,
              "y":926},
            "size":{
              "width":80,
              "height":80},
            "cornerRadiusTopLeft":"11"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80af9fbca1d34a46ab7fa213284ac3f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"40px",
                "location":{
                  "x":465,
                  "y":926},
                "size":{
                  "width":80,
                  "height":80},
                "cornerRadiusTopLeft":"11"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open help in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"help.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u8.png"}},
{
          "id":"ce6a3c546d4c4b01bb7e3560f717af47",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE8E8E8},
            "location":{
              "x":195,
              "y":135},
            "size":{
              "width":250,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43fed7f0f24c45d88ca33497e500f688",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE8E8E8},
                "location":{
                  "x":195,
                  "y":135},
                "size":{
                  "width":250,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u10.png"}},
{
          "id":"2b7b23b33a294e7991bc91a604c96f1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"35px",
            "location":{
              "x":95,
              "y":824},
            "size":{
              "width":450,
              "height":80},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b00ebbb60765469c9f9412b62fbbffef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"35px",
                "location":{
                  "x":95,
                  "y":824},
                "size":{
                  "width":450,
                  "height":80},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open mine in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"mine.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u2.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "fb7413fdc1924269815cac7df782d215":{
      "scriptId":"u0"},
    "d17f744c2b6a4d9c8ace3dc1752aac24":{
      "scriptId":"u1"},
    "9301769a44f44ab2a0d5c61bbc4ed7e1":{
      "scriptId":"u2"},
    "531568fbfc4a4affa2289d624a38fda4":{
      "scriptId":"u3"},
    "3b1f9de2e2db4f8e9b4447c8bc5d0002":{
      "scriptId":"u4"},
    "0e4205be0f4f4b6fa2d6b3ba9fd3c06f":{
      "scriptId":"u5"},
    "5cf7f7b8016845b0878ed6cb199d0c4d":{
      "scriptId":"u6"},
    "e5c4ee5157ea4f77aac8f219126c7b93":{
      "scriptId":"u7"},
    "72a2d3179bb74b23ab35e43d8fd659ce":{
      "scriptId":"u8"},
    "80af9fbca1d34a46ab7fa213284ac3f5":{
      "scriptId":"u9"},
    "ce6a3c546d4c4b01bb7e3560f717af47":{
      "scriptId":"u10"},
    "43fed7f0f24c45d88ca33497e500f688":{
      "scriptId":"u11"},
    "2b7b23b33a294e7991bc91a604c96f1d":{
      "scriptId":"u12"},
    "b00ebbb60765469c9f9412b62fbbffef":{
      "scriptId":"u13"}}});