$axure.loadCurrentPage({
  "url":"mine.html",
  "generationDate":new Date(1386580812074.54),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f527c7ced6674f069dc7328b3ccb1186",
    "type":"Axure:Page",
    "name":"mine",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5d080ecbc23341578fc38a9c07b68051",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64476a01eb4e425fb6a66a4a2358ee65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"7eba425213b54c70a5a56e918de8cf16",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"35px",
            "location":{
              "x":0,
              "y":1},
            "size":{
              "width":640,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7403273a8cd54f2484806c7940f8c5be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"35px",
                "location":{
                  "x":0,
                  "y":1},
                "size":{
                  "width":640,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u2.png"}},
{
          "id":"426c0404e6e34ba4818a89aacffceac9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":26},
            "size":{
              "width":50,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7bc95aaca9942799e64fada7879945f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22,
                  "y":26},
                "size":{
                  "width":50,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u4.png"}},
{
          "id":"ae58bfed6d2749ba9976ca3f115c8e6c",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"35px",
            "location":{
              "x":220,
              "y":260},
            "size":{
              "width":200,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72e84f9be88b4f40b86778f66632d709",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"35px",
                "location":{
                  "x":220,
                  "y":260},
                "size":{
                  "width":200,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_2/u6.png"}},
{
          "id":"95c85edb8a4d4683ad58f1d6b97f47d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "location":{
              "x":102,
              "y":546},
            "size":{
              "width":61,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3c04916b85d446089dccd408b213de8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "location":{
                  "x":102,
                  "y":546},
                "size":{
                  "width":61,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc3c4fddedb74711bcbfd74e02510dad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "location":{
              "x":102,
              "y":634},
            "size":{
              "width":61,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdc663cf5c72449c823266c07fcf6d9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "location":{
                  "x":102,
                  "y":634},
                "size":{
                  "width":61,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9226db053c44eafbf905ac606138aae",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":537},
            "size":{
              "width":350,
              "height":60}},
          "adaptiveStyles":{
}},
{
          "id":"338caccc71fe45b0a20075cc1311a916",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":630},
            "size":{
              "width":350,
              "height":60}},
          "adaptiveStyles":{
}},
{
          "id":"08f1242c02c949219466d4a4e15fe5ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "location":{
              "x":438,
              "y":730},
            "size":{
              "width":100,
              "height":60},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"233fc9757fa94b9ab32a2fca1596c189",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "location":{
                  "x":438,
                  "y":730},
                "size":{
                  "width":100,
                  "height":60},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 个人中心 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_2/u16.png"}},
{
          "id":"57c3dc53a95048f0ab33c69a10ef2a31",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "location":{
              "x":530,
              "y":11},
            "size":{
              "width":100,
              "height":60},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e739cf1a20eb4fceb588660813c64531",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "location":{
                  "x":530,
                  "y":11},
                "size":{
                  "width":100,
                  "height":60},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 注册 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"注册.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_2/u18.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "5d080ecbc23341578fc38a9c07b68051":{
      "scriptId":"u0"},
    "64476a01eb4e425fb6a66a4a2358ee65":{
      "scriptId":"u1"},
    "7eba425213b54c70a5a56e918de8cf16":{
      "scriptId":"u2"},
    "7403273a8cd54f2484806c7940f8c5be":{
      "scriptId":"u3"},
    "426c0404e6e34ba4818a89aacffceac9":{
      "scriptId":"u4"},
    "d7bc95aaca9942799e64fada7879945f":{
      "scriptId":"u5"},
    "ae58bfed6d2749ba9976ca3f115c8e6c":{
      "scriptId":"u6"},
    "72e84f9be88b4f40b86778f66632d709":{
      "scriptId":"u7"},
    "95c85edb8a4d4683ad58f1d6b97f47d3":{
      "scriptId":"u8"},
    "f3c04916b85d446089dccd408b213de8":{
      "scriptId":"u9"},
    "cc3c4fddedb74711bcbfd74e02510dad":{
      "scriptId":"u10"},
    "cdc663cf5c72449c823266c07fcf6d9a":{
      "scriptId":"u11"},
    "f9226db053c44eafbf905ac606138aae":{
      "scriptId":"u12"},
    "338caccc71fe45b0a20075cc1311a916":{
      "scriptId":"u13"},
    "08f1242c02c949219466d4a4e15fe5ca":{
      "scriptId":"u14"},
    "233fc9757fa94b9ab32a2fca1596c189":{
      "scriptId":"u15"},
    "57c3dc53a95048f0ab33c69a10ef2a31":{
      "scriptId":"u16"},
    "e739cf1a20eb4fceb588660813c64531":{
      "scriptId":"u17"}}});